ALG: APQN
EXP_NAME: apqn
PIXEL_BASED: False
NATIVE_DOWNSCALING: True

TOTAL_TIMESTEPS: 10000000

NUM_ENVS: 32
LEARNING_RATE: 2.5e-4
NUM_MINIBATCHES: 4
UPDATE_EPOCHS: 2
GAMMA: 0.99
Q_LAMBDA: 0.65
MAX_GRAD_NORM: 10.0
ANNEAL_LR: False
START_E: 1.0
END_E: 0.001
EXPLORATION_FRACTION: 0.10

NUM_STEPS_MIN: 16
NUM_STEPS_MAX: 64
ADAPT_FREQ: 50
POLICY_CHANGE_LOW: 0.05
POLICY_CHANGE_HIGH: 0.95
EMA_BETA: 0.1
REF_BATCH_SIZE: 2048
DIV_WINDOW: 10
