ALG: C51
EXP_NAME: c51

PIXEL_BASED: True
NATIVE_DOWNSCALING: True
NUM_ENVS: 1

TOTAL_TIMESTEPS: 10000000
BUFFER_SIZE: 40000
LEARNING_STARTS: 10000
TARGET_NETWORK_FREQUENCY: 10000
CHUNK_SIZE: 1000

LEARNING_RATE: 0.00025
BATCH_SIZE: 32
TRAIN_FREQUENCY: 1
GAMMA: 0.99
START_E: 1.0
END_E: 0.01
EXPLORATION_FRACTION: 0.10

N_ATOMS: 51
V_MIN: -10.0
V_MAX: 10.0

EVAL_EVERY: 10
SAVE_PATH: ./models
