ALG: DDPG
EXP_NAME: ddpg

PIXEL_BASED: True
NATIVE_DOWNSCALING: True
NUM_ENVS: 1

TOTAL_TIMESTEPS: 10000000
BUFFER_SIZE: 100000
LEARNING_STARTS: 10000
CHUNK_SIZE: 1000

ACTOR_LR: 0.0003
CRITIC_LR: 0.0003
BATCH_SIZE: 32
TRAIN_FREQUENCY: 4
GAMMA: 0.99
TAU: 0.005
VARIANT: gumbel_st
GUMBEL_TAU_START: 2.0
GUMBEL_TAU_END: 0.5
GUMBEL_TAU: 1.0
START_E: 1.0
END_E: 0.01
EXPLORATION_FRACTION: 0.10

EVAL_EVERY: 10
SAVE_PATH: ./models

RUN_NAME: v1_ddpg_rgb_original
