ALG: PPO
EXP_NAME: ppo

PIXEL_BASED: False
NATIVE_DOWNSCALING: True

TOTAL_TIMESTEPS: 1e7 #10M
LEARNING_RATE: 2.5e-4
NUM_ENVS: 16
NUM_STEPS: 128
ANNEAL_LR: True
GAMMA: 0.99
GAE_LAMBDA: 0.95
NUM_MINIBATCHES: 4 #512
UPDATE_EPOCHS: 2
NORM_ADV: True
CLIP_COEF: 0.1
CLIP_VLOSS: False
ENT_COEF: 0.01
VF_COEF: 0.5
MAX_GRAD_NORM: 0.5
TARGET_KL: 0.02 
