ALG: PQN
EXP_NAME: pqn
ENV_ID: pong

PIXEL_BASED: False

TOTAL_TIMESTEPS: 10000000
NUM_ENVS: 8
NUM_STEPS: 32
LEARNING_RATE: 2.5e-4
ANNEAL_LR: False
GAMMA: 0.99
Q_LAMBDA: 0.65
NUM_MINIBATCHES: 4
UPDATE_EPOCHS: 2
MAX_GRAD_NORM: 10.0
START_E: 1.0
END_E: 0.001
EXPLORATION_FRACTION: 0.10
