ALG: PQN
EXP_NAME: pqn

PIXEL_BASED: False
NATIVE_DOWNSCALING: True

TOTAL_TIMESTEPS: 10000000
NUM_STEPS: 128
SCAN_STEPS: 1000

NUM_ENVS: 8
LEARNING_RATE: 2.5e-4
NUM_MINIBATCHES: 4
UPDATE_EPOCHS: 4
GAMMA: 0.99
Q_LAMBDA: 0.65
MAX_GRAD_NORM: 10.0
ANNEAL_LR: True
START_E: 1.0
END_E: 0.01
EXPLORATION_FRACTION: 0.10