ALG: SIMBA_SAC
EXP_NAME: simba_sac

PIXEL_BASED: True
NATIVE_DOWNSCALING: True

LEARNING_RATE: 0.0003
GAMMA: 0.99
TAU: 1.0
BATCH_SIZE: 64
BUFFER_SIZE: 50000
LEARNING_STARTS: 20000
TRAIN_FREQUENCY: 4
GRADIENT_STEPS: 16
TARGET_UPDATE_FREQUENCY: 8000

AUTOTUNE: True
TARGET_ENTROPY_SCALE: 0.89
ALPHA: 0.2

SCAN_STEPS: 1000
NUM_ENVS: 16
TOTAL_TIMESTEPS: 10000000

SIMBA_ACTOR_HIDDEN_DIM: 128
SIMBA_ACTOR_NUM_BLOCKS: 1
SIMBA_CRITIC_HIDDEN_DIM: 512
SIMBA_CRITIC_NUM_BLOCKS: 2
SIMBA_EXPANSION_FACTOR: 4
